name: No Play So Long
main: me.ryandowling.noplaysolong.NoPlaySoLong
version: 0.0.0.1
commands:
  playtime:
    description: Gets the amount of time a user has been playing for. Leave user out for self.
    aliases: pt
permissions:
  noplaysolong.*:
    description: Gives access to all No Play So Long commands
    children:
      noplaysolong.playtime.self: true
      noplaysolong.playtime.others: true
  noplaysolong.playtime.self:
    description: Gives access to the /playtime command to check own playtime
    default: true
  noplaysolong.playtime.others:
    description: Gives access to the /playtime command to check others playtime
    default: op