name: No Play So Long
main: me.ryandowling.noplaysolong.NoPlaySoLong
version: 0.0.0.1
commands:
  playtime:
    description: Commands for the No Play So Long plugin relating to players time played.
    aliases: pt
permissions:
  noplaysolong.*:
    description: Gives access to all No Play So Long commands.
    children:
      noplaysolong.playtime.check.add: true
      noplaysolong.playtime.check.remove: true
      noplaysolong.playtime.check.self: true
      noplaysolong.playtime.check.others: true
  noplaysolong.playtime.add:
    description: Gives access to be able to add time to a players play time.
    default: op
  noplaysolong.playtime.remove:
    description: Gives access to be able to remove time from a players play time.
    default: op
  noplaysolong.playtime.check.self:
    description: Gives access to the /playtime check command to check own playtime.
    default: true
  noplaysolong.playtime.check.others:
    description: Gives access to the /playtime check command to check others playtime.
    default: op